# Generated by Django 5.0.1 on 2024-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='c_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
