# Generated by Django 5.0.1 on 2024-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('creat_date', models.DateTimeField()),
                ('updat_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
