# Generated by Django 5.0.1 on 2024-02-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
