# Generated by Django 5.0.1 on 2024-02-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img_alter_post_creat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
